//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Habr.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Habr.ConsoleApp.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What do you want to do? Please enter:.
        /// </summary>
        internal static string ActionSelection {
            get {
                return ResourceManager.GetString("ActionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authenticated user does not have a valid email.
        /// </summary>
        internal static string AuthenticatedUserNoValidEmail {
            get {
                return ResourceManager.GetString("AuthenticatedUserNoValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author&apos;s Email.
        /// </summary>
        internal static string AuthorEmail {
            get {
                return ResourceManager.GetString("AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Author&apos;s Email: {0}.
        /// </summary>
        internal static string AuthorEmailWithColon {
            get {
                return ResourceManager.GetString("AuthorEmailWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization was successful. Welcome back, {0}!.
        /// </summary>
        internal static string AuthorizationSuccessful {
            get {
                return ResourceManager.GetString("AuthorizationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization was successful. Welcome back, {0}!.
        /// </summary>
        internal static string AuthorizationWasSuccessful {
            get {
                return ResourceManager.GetString("AuthorizationWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}, your comment has been successfully added!.
        /// </summary>
        internal static string CommentAddedSuccessfully {
            get {
                return ResourceManager.GetString("CommentAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment deleted!.
        /// </summary>
        internal static string CommentDeleted {
            get {
                return ResourceManager.GetString("CommentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments:.
        /// </summary>
        internal static string CommentsWithColon {
            get {
                return ResourceManager.GetString("CommentsWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A - for add comment to post;.
        /// </summary>
        internal static string CommentToPost {
            get {
                return ResourceManager.GetString("CommentToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C - for confirm email;.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на C - for create post;.
        /// </summary>
        internal static string CreatePost {
            get {
                return ResourceManager.GetString("CreatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current user: {0}.
        /// </summary>
        internal static string CurrentUserName {
            get {
                return ResourceManager.GetString("CurrentUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of Creation.
        /// </summary>
        internal static string DateCreation {
            get {
                return ResourceManager.GetString("DateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date of Last Update.
        /// </summary>
        internal static string DateLastUpdate {
            get {
                return ResourceManager.GetString("DateLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date and Time of Publication.
        /// </summary>
        internal static string DatePublication {
            get {
                return ResourceManager.GetString("DatePublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date and Time of Publication: {0}.
        /// </summary>
        internal static string DatePublicationWithColon {
            get {
                return ResourceManager.GetString("DatePublicationWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection string &apos;DefaultConnection&apos; is empty. Please check your settings!.
        /// </summary>
        internal static string DefaultConnectionEmpty {
            get {
                return ResourceManager.GetString("DefaultConnectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X - for delete comment;.
        /// </summary>
        internal static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на D - for delete post;.
        /// </summary>
        internal static string DeletePost {
            get {
                return ResourceManager.GetString("DeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на n - Display the current user&apos;s name.
        /// </summary>
        internal static string DisplayUserName {
            get {
                return ResourceManager.GetString("DisplayUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t forget to confirm your email!.
        /// </summary>
        internal static string DonNotForgetConfirmEmail {
            get {
                return ResourceManager.GetString("DonNotForgetConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E - for edit post;.
        /// </summary>
        internal static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email confirmation cancelled..
        /// </summary>
        internal static string EmailConfirmationCancelled {
            get {
                return ResourceManager.GetString("EmailConfirmationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email confirmation failed. Please try again..
        /// </summary>
        internal static string EmailConfirmationFailed {
            get {
                return ResourceManager.GetString("EmailConfirmationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email confirmed..
        /// </summary>
        internal static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email confirmed successfully..
        /// </summary>
        internal static string EmailConfirmedSuccessfully {
            get {
                return ResourceManager.GetString("EmailConfirmedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email not confirmed - please confirm your email later..
        /// </summary>
        internal static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the ID of the comment you want to delete:.
        /// </summary>
        internal static string EnterCommentIDToDelete {
            get {
                return ResourceManager.GetString("EnterCommentIDToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the ID of the comment you want to reply to:.
        /// </summary>
        internal static string EnterCommentIDToReply {
            get {
                return ResourceManager.GetString("EnterCommentIDToReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your email.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter new text:.
        /// </summary>
        internal static string EnterNewText {
            get {
                return ResourceManager.GetString("EnterNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter new title:.
        /// </summary>
        internal static string EnterNewTitle {
            get {
                return ResourceManager.GetString("EnterNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter the number {0} to confirm your email:.
        /// </summary>
        internal static string EnterNumberToConfirmEmail {
            get {
                return ResourceManager.GetString("EnterNumberToConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter post ID:.
        /// </summary>
        internal static string EnterPostID {
            get {
                return ResourceManager.GetString("EnterPostID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the ID of the post you want to comment on:.
        /// </summary>
        internal static string EnterPostIDToComment {
            get {
                return ResourceManager.GetString("EnterPostIDToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the ID of the post you want to delete:.
        /// </summary>
        internal static string EnterPostIDToDelete {
            get {
                return ResourceManager.GetString("EnterPostIDToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the ID of the post you want to edit:.
        /// </summary>
        internal static string EnterPostIDToEdit {
            get {
                return ResourceManager.GetString("EnterPostIDToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the ID of the post you want to move to drafts:.
        /// </summary>
        internal static string EnterPostIDToMoveToDrafts {
            get {
                return ResourceManager.GetString("EnterPostIDToMoveToDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the ID of the post you want to publish:.
        /// </summary>
        internal static string EnterPostIDToPublish {
            get {
                return ResourceManager.GetString("EnterPostIDToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter the ID of the post you want to see comments:.
        /// </summary>
        internal static string EnterPostIDToSeeComments {
            get {
                return ResourceManager.GetString("EnterPostIDToSeeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter post text:.
        /// </summary>
        internal static string EnterPostText {
            get {
                return ResourceManager.GetString("EnterPostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter post title:.
        /// </summary>
        internal static string EnterPostTitle {
            get {
                return ResourceManager.GetString("EnterPostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your comment:.
        /// </summary>
        internal static string EnterYourComment {
            get {
                return ResourceManager.GetString("EnterYourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your password.
        /// </summary>
        internal static string EnterYourPassword {
            get {
                return ResourceManager.GetString("EnterYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your reply:.
        /// </summary>
        internal static string EnterYourReply {
            get {
                return ResourceManager.GetString("EnterYourReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на G - for get all posts;.
        /// </summary>
        internal static string GetAllPosts {
            get {
                return ResourceManager.GetString("GetAllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID parent comment.
        /// </summary>
        internal static string IdParentComment {
            get {
                return ResourceManager.GetString("IdParentComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid action. Please try again..
        /// </summary>
        internal static string InvalidAction {
            get {
                return ResourceManager.GetString("InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid ID format..
        /// </summary>
        internal static string InvalidIDFormat {
            get {
                return ResourceManager.GetString("InvalidIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is the post published? (yes/no):.
        /// </summary>
        internal static string IsPostPublished {
            get {
                return ResourceManager.GetString("IsPostPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is Published.
        /// </summary>
        internal static string IsPublished {
            get {
                return ResourceManager.GetString("IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A - for login;.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на M - for move post to drafts;.
        /// </summary>
        internal static string MovePostToDrafts {
            get {
                return ResourceManager.GetString("MovePostToDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to be logged in to view posts..
        /// </summary>
        internal static string NeedToBeLogged {
            get {
                return ResourceManager.GetString("NeedToBeLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No comments found for this post!.
        /// </summary>
        internal static string NoCommentsFoundForPost {
            get {
                return ResourceManager.GetString("NoCommentsFoundForPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No draft posts found!.
        /// </summary>
        internal static string NoDraftPostsFound {
            get {
                return ResourceManager.GetString("NoDraftPostsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No posts found!.
        /// </summary>
        internal static string NoPostsFound {
            get {
                return ResourceManager.GetString("NoPostsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No published posts found!.
        /// </summary>
        internal static string NoPublishedPostsFound {
            get {
                return ResourceManager.GetString("NoPublishedPostsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter your email.
        /// </summary>
        internal static string PleaseEnterEmail {
            get {
                return ResourceManager.GetString("PleaseEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter &apos;yes&apos; or &apos;no&apos;..
        /// </summary>
        internal static string PleaseEnterYesOrNo {
            get {
                return ResourceManager.GetString("PleaseEnterYesOrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}, your post has been successfully created!.
        /// </summary>
        internal static string PostCreatedSuccessfully {
            get {
                return ResourceManager.GetString("PostCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post deleted!.
        /// </summary>
        internal static string PostDeleted {
            get {
                return ResourceManager.GetString("PostDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на J - for post details;.
        /// </summary>
        internal static string PostDetails {
            get {
                return ResourceManager.GetString("PostDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post Id.
        /// </summary>
        internal static string PostId {
            get {
                return ResourceManager.GetString("PostId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This post is published and cannot be edited. Move it to drafts first..
        /// </summary>
        internal static string PostIsPublishedCannotEdit {
            get {
                return ResourceManager.GetString("PostIsPublishedCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post moved to drafts successfully!.
        /// </summary>
        internal static string PostMovedToDraftsSuccessfully {
            get {
                return ResourceManager.GetString("PostMovedToDraftsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post not found..
        /// </summary>
        internal static string PostNotFound {
            get {
                return ResourceManager.GetString("PostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This post was not found for you!.
        /// </summary>
        internal static string PostNotFoundForYou {
            get {
                return ResourceManager.GetString("PostNotFoundForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post published!.
        /// </summary>
        internal static string PostPublished {
            get {
                return ResourceManager.GetString("PostPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post updated!.
        /// </summary>
        internal static string PostUpdated {
            get {
                return ResourceManager.GetString("PostUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на P - for publish post;.
        /// </summary>
        internal static string PublishPost {
            get {
                return ResourceManager.GetString("PublishPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на r.
        /// </summary>
        internal static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R - for register;.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration successful. Welcome, {0}!.
        /// </summary>
        internal static string RegistrationSuccessful {
            get {
                return ResourceManager.GetString("RegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}, your reply has been successfully added!.
        /// </summary>
        internal static string ReplyAddedSuccessfully {
            get {
                return ResourceManager.GetString("ReplyAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R - for reply to comment;.
        /// </summary>
        internal static string ReplyToComment {
            get {
                return ResourceManager.GetString("ReplyToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} | {1} | {2} | {3} | Parent Comment ID: {4}.
        /// </summary>
        internal static string TableFields {
            get {
                return ResourceManager.GetString("TableFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text: {0}.
        /// </summary>
        internal static string TextWithColon {
            get {
                return ResourceManager.GetString("TextWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title: {0}.
        /// </summary>
        internal static string TitleWithColon {
            get {
                return ResourceManager.GetString("TitleWithColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0 - to exit;.
        /// </summary>
        internal static string ToExit {
            get {
                return ResourceManager.GetString("ToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User is not authenticated.
        /// </summary>
        internal static string UserNotAuthenticated {
            get {
                return ResourceManager.GetString("UserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на S - for view draft posts;.
        /// </summary>
        internal static string ViewDraftPosts {
            get {
                return ResourceManager.GetString("ViewDraftPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What do you want to do? Please enter:.
        /// </summary>
        internal static string WhatDoYouWant {
            get {
                return ResourceManager.GetString("WhatDoYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have no comments to delete.
        /// </summary>
        internal static string YouHaveNoCommentsToDelete {
            get {
                return ResourceManager.GetString("YouHaveNoCommentsToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have no posts to delete.
        /// </summary>
        internal static string YouHaveNoPostsToDelete {
            get {
                return ResourceManager.GetString("YouHaveNoPostsToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have no posts to edit.
        /// </summary>
        internal static string YouHaveNoPostsToEdit {
            get {
                return ResourceManager.GetString("YouHaveNoPostsToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have no posts to move to drafts.
        /// </summary>
        internal static string YouHaveNoPostsToMoveToDrafts {
            get {
                return ResourceManager.GetString("YouHaveNoPostsToMoveToDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have no posts to publish.
        /// </summary>
        internal static string YouHaveNoPostsToPublish {
            get {
                return ResourceManager.GetString("YouHaveNoPostsToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} (or 0 to exit):.
        /// </summary>
        internal static string ZeroToExit {
            get {
                return ResourceManager.GetString("ZeroToExit", resourceCulture);
            }
        }
    }
}
